# Generated by Django 5.2 on 2025-12-05 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('published_on', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('source_id', models.IntegerField()),
                ('body', models.TextField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_on'],
                'indexes': [models.Index(fields=['-published_on'], name='news_newsar_publish_358bb7_idx'), models.Index(fields=['source_id'], name='news_newsar_source__5f0f01_idx'), models.Index(fields=['sentiment'], name='news_newsar_sentime_3faad7_idx')],
            },
        ),
    ]
