# Generated by Django 5.2 on 2025-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_price',
            field=models.FloatField(default=0.0),
        ),
    ]
