# Generated by Django 5.2 on 2025-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
    ]
