# Generated by Django 5.2 on 2025-06-30 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0004_asset_leverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.FloatField()),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('entry_price', models.FloatField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('leverage', models.IntegerField(default=1)),
                ('pnl', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss')], max_length=2)),
                ('price', models.FloatField()),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trade.position')),
            ],
        ),
    ]
