# Generated by Django 5.2 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='trading_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
