# Generated by Django 5.2 on 2025-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_position_trading_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
