# Generated by Django 5.2 on 2025-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_position_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='probability',
            field=models.FloatField(default=-1),
        ),
    ]
