# Generated by Django 5.2 on 2025-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_position_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.FloatField()),
                ('trade_pocket_balance', models.FloatField()),
                ('unrealized_pnl', models.FloatField()),
                ('unrealized_trade_balance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
