# Generated by Django 5.2 on 2025-07-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_leverage'),
        ('trade', '0005_balancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.FloatField()),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('entry_price', models.FloatField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('leverage', models.IntegerField(default=1)),
                ('trading_model', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('probability', models.FloatField(default=-1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
