# Generated by Django 5.2 on 2025-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_onewayposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='position',
            name='commission',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='position',
            name='order_commission',
            field=models.FloatField(default=-1),
        ),
    ]
