# Generated by Django 5.2 on 2025-05-08 10:32

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_symbol'),
        ('ohlc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle1D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='ohlc_candle_symbol__52eefd_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='ohlc_candle_timesta_b73471_brin', pages_per_range=128)],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
