# Generated by Django 5.2 on 2026-02-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0004_asset_leverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, help_text='Starting balance for demo account', max_digits=20)),
                ('max_open_positions', models.PositiveIntegerField(default=5, help_text='Maximum number of open trades allowed')),
                ('leverage', models.DecimalField(decimal_places=2, default=1.0, help_text='Leverage multiplier for trades', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo Configuration',
                'verbose_name_plural': 'Demo Configurations',
            },
        ),
        migrations.CreateModel(
            name='DemoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Whether this position is a Buy or Sell', max_length=4, verbose_name='Trade Side')),
                ('quantity', models.FloatField(help_text='Number of units in the position', verbose_name='Quantity')),
                ('entry_price', models.FloatField(help_text='Price at which the position was opened', verbose_name='Entry Price')),
                ('stop_loss', models.FloatField(blank=True, help_text='Price at which the position will be automatically closed to limit loss', null=True, verbose_name='Stop Loss')),
                ('take_profit', models.FloatField(blank=True, help_text='Price at which the position will be automatically closed to secure profit', null=True, verbose_name='Take Profit')),
                ('leverage', models.IntegerField(default=1, help_text='Leverage multiplier applied to this position', verbose_name='Leverage')),
                ('pnl', models.FloatField(default=0.0, help_text='Current profit or loss of this position', verbose_name='Profit/Loss')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the position', max_length=6, verbose_name='Status')),
                ('telegram_message_id', models.IntegerField(blank=True, help_text='Reference ID if this position was sent to Telegram', null=True, verbose_name='Telegram Message ID')),
                ('commission', models.FloatField(default=0, help_text='Commission cost for this trade', verbose_name='Commission')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Entry Time')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Exit Time')),
                ('exit_price', models.FloatField(blank=True, help_text='Price at which the position was closed', null=True, verbose_name='Exit Price')),
                ('asset', models.ForeignKey(help_text='The financial asset being traded', on_delete=django.db.models.deletion.CASCADE, to='asset.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Demo Position',
                'verbose_name_plural': 'Demo Positions',
                'ordering': ['-entry_time'],
            },
        ),
    ]
