# Generated by Django 5.2 on 2026-02-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='democonfig',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Balance available for opening new positions', max_digits=20),
        ),
        migrations.AddField(
            model_name='demoposition',
            name='margin_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of balance allocated for this position', max_digits=20, verbose_name='Margin Balance'),
        ),
        migrations.AlterField(
            model_name='demoposition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='PENDING', help_text='Current status of the position', max_length=8, verbose_name='Status'),
        ),
    ]
