# Generated by Django 5.2 on 2026-02-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_trade', '0002_democonfig_available_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoposition',
            name='leverage',
        ),
    ]
