# Generated by Django 5.2 on 2026-02-07 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_trade', '0003_remove_demoposition_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoposition',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demoposition',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry Time'),
        ),
    ]
